-- Enable pgvector extension for semantic search
create extension if not exists vector;

-- PRODUCTS TABLE
create table products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  description_html text, -- Generated by AI
  price decimal(10, 2) not null,
  currency text default 'USD',
  image_url text not null,
  stock_quantity integer default 0,
  tags jsonb default '[]', -- AI generated tags
  embedding vector(768), -- Gemini embedding dimension (check specific model, usually 768 or 1536)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- INDEX for semantic search
create index on products using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- INVENTORY LOGS (For AI War Room)
create table inventory_logs (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references products(id) on delete cascade,
  change_amount integer not null, -- +50 or -1
  reason text, -- 'sale', 'restock', 'correction'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REVIEWS (Sentinel System)
create table reviews (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references products(id) on delete cascade,
  user_id uuid not null, -- References auth.users
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  sentiment_score float, -- AI analysis
  is_toxic boolean default false,
  status text default 'pending', -- 'approved', 'rejected'
  admin_reply_draft text, -- AI generated draft
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDERS
create table orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null,
  total_amount decimal(10, 2) not null,
  status text default 'pending', -- 'paid', 'shipped', 'delivered'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ORDER ITEMS
create table order_items (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references orders(id) on delete cascade,
  product_id uuid references products(id),
  quantity integer not null,
  price_at_purchase decimal(10, 2) not null
);

-- FUNCTIONS

-- Search Products by vector similarity
create or replace function search_products (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id uuid,
  name text,
  description text,
  price decimal,
  similarity float
)
language sql stable
as $$
  select
    products.id,
    products.name,
    products.description,
    products.price,
    1 - (products.embedding <=> query_embedding) as similarity
  from products
  where 1 - (products.embedding <=> query_embedding) > match_threshold
  order by products.embedding <=> query_embedding
  limit match_count;
$$;
